SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:      RAFAEL HENRIQUE DE CARVALHO
-- CREATE DATE: 05/30/2026
-- DESCRIPTION: INSERTS A NEW TENANT INTO THE TENANTS TABLE
-- =============================================
CREATE OR ALTER PROCEDURE SP_CREATE_TENANT
    @NAME     NVARCHAR(200),
    @DOCUMENT NVARCHAR(18),
    @EMAIL    NVARCHAR(255),
    @PHONE    NVARCHAR(20) = NULL,
    @API_KEY  NVARCHAR(64)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TENANTS WHERE DOCUMENT = @DOCUMENT)
        THROW 99999, 'Document is already in use.', 1;

    IF EXISTS (SELECT 1 FROM TENANTS WHERE EMAIL = @EMAIL)
        THROW 99999, 'Email is already in use.', 1;

    INSERT INTO TENANTS (NAME, DOCUMENT, EMAIL, PHONE, APIKEY, ISACTIVE, CREATEDAT)
    VALUES (@NAME, @DOCUMENT, @EMAIL, @PHONE, @API_KEY, 1, GETUTCDATE())
END
GO