USE [NexusPay]
GO

/****** Object:  StoredProcedure [dbo].[SP_CREATE_USER]    Script Date: 5/22/2026 2:38:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- AUTHOR:      RAFAEL HENRIQUE DE CARVALHO
-- CREATE DATE: 05/17/2026
-- DESCRIPTION: INSERTS A NEW USER INTO THE USERS TABLE
-- =============================================
CREATE OR ALTER     PROCEDURE [dbo].[SP_CREATE_USER]
    @NAME NVARCHAR(100),
    @EMAIL NVARCHAR(255),
    @HASHED_PASSWORD NVARCHAR(255),
	@ROLE_ID INT
AS
BEGIN
    SET NOCOUNT ON;

	BEGIN TRY

	IF EXISTS (SELECT 1 FROM USERS WHERE EMAIL = @EMAIL)
		THROW 99999, 'Email is already in use.', 1;

	IF NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = @ROLE_ID)
        THROW 99999, 'Invalid role.', 1;

    INSERT INTO USERS (NAME, EMAIL, PASSWORDHASH, ROLEID, CREATEDAT, ISACTIVE)
    VALUES (@NAME, @EMAIL, @HASHED_PASSWORD, @ROLE_ID, GETUTCDATE(), 1)

	END TRY
    BEGIN CATCH

		THROW;

	END CATCH

END
GO


