USE [NexusPay]
GO
/****** Object:  StoredProcedure [dbo].[SP_LOGIN_USER]    Script Date: 5/22/2026 1:50:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:      RAFAEL HENRIQUE DE CARVALHO
-- CREATE DATE: 05/17/2026
-- DESCRIPTION: RETRIEVES USER CREDENTIALS BY EMAIL FOR AUTHENTICATION
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[SP_LOGIN_USER]
    @EMAIL NVARCHAR(255)
AS
BEGIN

    SET NOCOUNT ON;
    
	IF (@EMAIL IS NULL OR @EMAIL = '')
		THROW 99999, 'Email is required.', 1;

    ELSE 
	   BEGIN
		 SELECT U.ID, U.NAME, EMAIL, PASSWORDHASH, R.NAME AS ROLE
			FROM USERS U
			INNER JOIN ROLES R ON R.ID = U.ROLEID
			WHERE EMAIL = @EMAIL AND U.ISACTIVE = 1
	   END

END;
