USE [NexusPay]
GO
/****** Object:  StoredProcedure [dbo].[SP_CREATE_USER]    Script Date: 5/20/2026 10:38:14 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:      RAFAEL HENRIQUE DE CARVALHO
-- CREATE DATE: 05/17/2026
-- DESCRIPTION: INSERTS A NEW USER INTO THE USERS TABLE
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[SP_CREATE_USER]
    @NAME NVARCHAR(100),
    @EMAIL NVARCHAR(255),
    @HASHED_PASSWORD NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

	IF EXISTS (SELECT 1 FROM USERS WHERE EMAIL = @EMAIL)
		THROW 99999, 'EMAIL ALREADY EXISTS, PLEASE VERIFY!', 1;

    INSERT INTO USERS (NAME, EMAIL, PASSWORDHASH, CREATEDAT, ISACTIVE)
    VALUES (@NAME, @EMAIL, @HASHED_PASSWORD, GETUTCDATE(), 1)
END
